# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Complex_Gui_2_Loci.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LociGui(object):
    def setupUi(self, LociGui):
        LociGui.setObjectName("LociGui")
        LociGui.resize(1111, 522)
        self.verticalLayoutWidget = QtWidgets.QWidget(LociGui)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 511, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(16, 14))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.RealPartBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.RealPartBox.setMinimum(-99.99)
        self.RealPartBox.setObjectName("RealPartBox")
        self.verticalLayout_2.addWidget(self.RealPartBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.ImaginaryPartBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.ImaginaryPartBox.setMinimum(-99.99)
        self.ImaginaryPartBox.setObjectName("ImaginaryPartBox")
        self.verticalLayout_3.addWidget(self.ImaginaryPartBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.RadiusBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.RadiusBox.setObjectName("RadiusBox")
        self.horizontalLayout.addWidget(self.RadiusBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.MakeCircleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MakeCircleButton.setObjectName("MakeCircleButton")
        self.horizontalLayout.addWidget(self.MakeCircleButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.ThetaBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.ThetaBox.setMinimum(-3.14)
        self.ThetaBox.setMaximum(3.14)
        self.ThetaBox.setSingleStep(0.03)
        self.ThetaBox.setObjectName("ThetaBox")
        self.horizontalLayout_4.addWidget(self.ThetaBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.MakeHalfLineButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MakeHalfLineButton.setObjectName("MakeHalfLineButton")
        self.horizontalLayout_4.addWidget(self.MakeHalfLineButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.BisectRealBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.BisectRealBox.setMinimum(-99.99)
        self.BisectRealBox.setObjectName("BisectRealBox")
        self.horizontalLayout_3.addWidget(self.BisectRealBox)
        self.BisectImBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.BisectImBox.setMinimum(-99.99)
        self.BisectImBox.setObjectName("BisectImBox")
        self.horizontalLayout_3.addWidget(self.BisectImBox)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.MakeBisectorButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MakeBisectorButton.setObjectName("MakeBisectorButton")
        self.horizontalLayout_3.addWidget(self.MakeBisectorButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.undoButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_5.addWidget(self.undoButton)
        self.clearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(LociGui)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 10, 571, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.InsertGraph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.InsertGraph.setContentsMargins(0, 0, 0, 0)
        self.InsertGraph.setObjectName("InsertGraph")

        self.retranslateUi(LociGui)
        QtCore.QMetaObject.connectSlotsByName(LociGui)

    def retranslateUi(self, LociGui):
        _translate = QtCore.QCoreApplication.translate
        LociGui.setWindowTitle(_translate("LociGui", "Loci"))
        self.label_4.setText(_translate("LociGui", "Real Part"))
        self.label_5.setText(_translate("LociGui", "Imaginary Part"))
        self.label.setText(_translate("LociGui", "Radius"))
        self.MakeCircleButton.setText(_translate("LociGui", "Circle"))
        self.label_3.setText(_translate("LociGui", "Angle"))
        self.MakeHalfLineButton.setText(_translate("LociGui", "Half-Line"))
        self.label_2.setText(_translate("LociGui", "Complex"))
        self.MakeBisectorButton.setText(_translate("LociGui", "Bisector"))
        self.undoButton.setText(_translate("LociGui", "Undo"))
        self.clearButton.setText(_translate("LociGui", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LociGui = QtWidgets.QDialog()
    ui = Ui_LociGui()
    ui.setupUi(LociGui)
    LociGui.show()
    sys.exit(app.exec_())

