# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Complex_Gui_3_Calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_C(object):
    def setupUi(self, C):
        C.setObjectName("C")
        C.resize(779, 674)
        self.verticalLayoutWidget = QtWidgets.QWidget(C)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(16, 14))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.RealPartBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.RealPartBox.setMinimum(-99990000.0)
        self.RealPartBox.setMaximum(99990000.0)
        self.RealPartBox.setObjectName("RealPartBox")
        self.verticalLayout_2.addWidget(self.RealPartBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.ImaginaryPartBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.ImaginaryPartBox.setMinimum(-99990000.0)
        self.ImaginaryPartBox.setMaximum(99990000.0)
        self.ImaginaryPartBox.setObjectName("ImaginaryPartBox")
        self.verticalLayout_3.addWidget(self.ImaginaryPartBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.RootButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RootButton.setObjectName("RootButton")
        self.gridLayout.addWidget(self.RootButton, 2, 0, 1, 1)
        self.MultiplyButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MultiplyButton.setObjectName("MultiplyButton")
        self.gridLayout.addWidget(self.MultiplyButton, 1, 0, 1, 1)
        self.DivideButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DivideButton.setObjectName("DivideButton")
        self.gridLayout.addWidget(self.DivideButton, 1, 1, 1, 1)
        self.ConjButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConjButton.setObjectName("ConjButton")
        self.gridLayout.addWidget(self.ConjButton, 2, 1, 1, 1)
        self.SubtractionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SubtractionButton.setObjectName("SubtractionButton")
        self.gridLayout.addWidget(self.SubtractionButton, 0, 1, 1, 1)
        self.AdditionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.AdditionButton.setObjectName("AdditionButton")
        self.gridLayout.addWidget(self.AdditionButton, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(16, 14))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.RealPartBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.RealPartBox_2.setMinimum(-99990000.0)
        self.RealPartBox_2.setMaximum(99990000.0)
        self.RealPartBox_2.setObjectName("RealPartBox_2")
        self.verticalLayout_4.addWidget(self.RealPartBox_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.ImaginaryPartBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.ImaginaryPartBox_2.setMinimum(-99990000.0)
        self.ImaginaryPartBox_2.setObjectName("ImaginaryPartBox_2")
        self.verticalLayout_5.addWidget(self.ImaginaryPartBox_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(C)
        QtCore.QMetaObject.connectSlotsByName(C)

    def retranslateUi(self, C):
        _translate = QtCore.QCoreApplication.translate
        C.setWindowTitle(_translate("C", "Calculator"))
        self.label.setText(_translate("C", "Real Part"))
        self.label_2.setText(_translate("C", "Imaginary Part"))
        self.RootButton.setText(_translate("C", "*Root*"))
        self.MultiplyButton.setText(_translate("C", "Multiply"))
        self.DivideButton.setText(_translate("C", "Divide"))
        self.ConjButton.setText(_translate("C", "*Conjugate*"))
        self.SubtractionButton.setText(_translate("C", "Subtract"))
        self.AdditionButton.setText(_translate("C", "Add"))
        self.label_5.setText(_translate("C", "* - Doesn\'t require another number"))
        self.label_3.setText(_translate("C", "Real Part"))
        self.label_4.setText(_translate("C", "Imaginary Part"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    C = QtWidgets.QDialog()
    ui = Ui_C()
    ui.setupUi(C)
    C.show()
    sys.exit(app.exec_())

