# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Matrix_Transformation_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1087, 924)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 861, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.functionInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.functionInput.setObjectName("functionInput")
        self.horizontalLayout.addWidget(self.functionInput)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.SquareDim = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.SquareDim.setMinimum(0.01)
        self.SquareDim.setObjectName("SquareDim")
        self.horizontalLayout.addWidget(self.SquareDim)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.MakeGraph = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MakeGraph.setObjectName("MakeGraph")
        self.horizontalLayout_2.addWidget(self.MakeGraph)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.SquareButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SquareButton.setObjectName("SquareButton")
        self.horizontalLayout_2.addWidget(self.SquareButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.UndoButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.UndoButton.setObjectName("UndoButton")
        self.horizontalLayout_2.addWidget(self.UndoButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.ClearGraph = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ClearGraph.setObjectName("ClearGraph")
        self.horizontalLayout_2.addWidget(self.ClearGraph)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.ApplyTransformation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ApplyTransformation.setObjectName("ApplyTransformation")
        self.horizontalLayout_2.addWidget(self.ApplyTransformation)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 1061, 821))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.InsertGraphInto = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.InsertGraphInto.setContentsMargins(0, 0, 0, 0)
        self.InsertGraphInto.setObjectName("InsertGraphInto")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(890, 10, 181, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TopLeftMatrix = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.TopLeftMatrix.setDecimals(3)
        self.TopLeftMatrix.setMinimum(-99.999)
        self.TopLeftMatrix.setMaximum(99.999)
        self.TopLeftMatrix.setObjectName("TopLeftMatrix")
        self.gridLayout.addWidget(self.TopLeftMatrix, 0, 0, 1, 1)
        self.BottomLeftMatrix = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.BottomLeftMatrix.setDecimals(3)
        self.BottomLeftMatrix.setMinimum(-99.999)
        self.BottomLeftMatrix.setMaximum(99.999)
        self.BottomLeftMatrix.setObjectName("BottomLeftMatrix")
        self.gridLayout.addWidget(self.BottomLeftMatrix, 1, 0, 1, 1)
        self.TopRightMatrix = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.TopRightMatrix.setDecimals(3)
        self.TopRightMatrix.setMinimum(-99.999)
        self.TopRightMatrix.setMaximum(99.999)
        self.TopRightMatrix.setObjectName("TopRightMatrix")
        self.gridLayout.addWidget(self.TopRightMatrix, 0, 1, 1, 1)
        self.BottomRightMatrix = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.BottomRightMatrix.setDecimals(3)
        self.BottomRightMatrix.setMinimum(-99.999)
        self.BottomRightMatrix.setMaximum(99.999)
        self.BottomRightMatrix.setObjectName("BottomRightMatrix")
        self.gridLayout.addWidget(self.BottomRightMatrix, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Matrix Transformations"))
        self.label.setText(_translate("Dialog", "Plot y ="))
        self.label_2.setText(_translate("Dialog", "Square Dimensions"))
        self.MakeGraph.setText(_translate("Dialog", "Make Graph"))
        self.SquareButton.setText(_translate("Dialog", "Square"))
        self.UndoButton.setText(_translate("Dialog", "Undo"))
        self.ClearGraph.setText(_translate("Dialog", "Clear"))
        self.ApplyTransformation.setText(_translate("Dialog", "Apply Transformation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

